# Generated by Django 2.0.2 on 2018-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0002_auto_20180227_1101")]

    operations = [
        migrations.AlterField(model_name="client", name="email", field=models.TextField(null=True)),
        migrations.AlterField(
            model_name="client", name="note", field=models.TextField(blank=True, null=True)
        ),
        migrations.AlterField(model_name="client", name="phone", field=models.TextField(null=True)),
    ]
