# Generated by Django 2.0.2 on 2018-03-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admin", "0004_auto_20180304_1058")]

    operations = [
        migrations.RenameField(
            model_name="attendance", old_name="attendancestate", new_name="attendance_state"
        )
    ]
