# Generated by Django 2.0.2 on 2018-03-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0006_auto_20180304_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attendancestate',
            new_name='attendance_state',
        ),
    ]
