# Generated by Django 2.0.2 on 2018-03-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0008_auto_20180305_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendancestate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.AttendanceState'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='admin.Client'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='admin.Lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin.Course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='admin.Group'),
        ),
        migrations.AlterField(
            model_name='memberof',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberof', to='admin.Client'),
        ),
        migrations.AlterField(
            model_name='memberof',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberof', to='admin.Group'),
        ),
    ]
