# Generated by Django 2.0.3 on 2018-03-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0010_auto_20180307_1753")]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
