# Generated by Django 2.0.3 on 2018-03-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0012_auto_20180310_1942")]

    operations = [
        migrations.AddField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="admin.Course"
            ),
            preserve_default=False,
        )
    ]
