# Generated by Django 2.0.3 on 2018-03-21 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0014_auto_20180321_1254")]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendancestate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="admin.AttendanceState"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="admin.Course"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="admin.Course"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="admin.Group",
            ),
        ),
        migrations.AlterField(
            model_name="lecture", name="start", field=models.DateTimeField(null=True)
        ),
        migrations.AlterField(
            model_name="membership", name="end", field=models.DateTimeField(null=True)
        ),
    ]
