# Generated by Django 2.0.3 on 2018-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0015_auto_20180321_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='end',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='start',
        ),
    ]
