# Generated by Django 2.0.3 on 2018-03-23 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0017_auto_20180323_0903")]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="attendancestate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="admin.AttendanceState"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="admin.Course"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="admin.Course"),
        ),
    ]
