# Generated by Django 2.0.3 on 2018-03-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0019_auto_20180323_0920")]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="admin.Client",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="admin.Lecture",
            ),
        ),
    ]
