# Generated by Django 2.0.6 on 2018-07-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admin", "0027_application")]

    operations = [migrations.AlterModelOptions(name="application", options={})]
