# Generated by Django 2.1.1 on 2018-09-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0031_auto_20180830_1708")]

    operations = [migrations.AlterField(model_name="group", name="name", field=models.TextField())]
