# Generated by Django 2.1.1 on 2018-09-26 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0032_auto_20180925_2114")]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.TextField(
                blank=True, validators=[django.core.validators.MinLengthValidator(9)]
            ),
        )
    ]
