# Generated by Django 2.1.1 on 2018-09-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0033_auto_20180926_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
