# Generated by Django 2.1.5 on 2019-01-28 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0035_course_duration")]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="admin.Course"
            ),
        )
    ]
