# Generated by Django 2.2.1 on 2019-05-14 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0038_auto_20190209_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='admin.Course'),
            preserve_default=False,
        ),
    ]
