# Generated by Django 2.2.3 on 2019-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admin", "0039_auto_20190514_2149")]

    operations = [
        migrations.AlterModelOptions(
            name="application", options={"ordering": ["client__surname", "client__name"]}
        )
    ]
