# Generated by Django 2.2.3 on 2019-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0040_auto_20190718_0938")]

    operations = [
        migrations.AddField(
            model_name="course", name="color", field=models.CharField(default="#000", max_length=7)
        )
    ]
