# Generated by Django 2.2.4 on 2019-08-11 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0041_course_color")]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="color",
            field=models.CharField(
                default="#000000",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Barva není v HEX formátu", regex="^#(?:[0-9a-fA-F]{3}){1,2}$"
                    )
                ],
            ),
        )
    ]
