# Generated by Django 2.2.4 on 2019-09-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0042_auto_20190811_1442")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="created_at",
            field=models.DateField(default="2019-01-01"),
        )
    ]
