# Generated by Django 2.2.4 on 2019-09-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0043_application_created_at")]

    operations = [
        migrations.AlterField(
            model_name="application", name="created_at", field=models.DateField(auto_now_add=True)
        )
    ]
