# Generated by Django 2.2.5 on 2019-09-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("admin", "0044_auto_20190901_1457")]

    operations = [
        migrations.AlterModelOptions(
            name="application", options={"ordering": ["client__surname", "client__firstname"]}
        ),
        migrations.AlterModelOptions(
            name="attendance", options={"ordering": ["client__surname", "client__firstname"]}
        ),
        migrations.AlterModelOptions(name="client", options={"ordering": ["surname", "firstname"]}),
        migrations.AlterModelOptions(
            name="membership", options={"ordering": ["client__surname", "client__firstname"]}
        ),
        migrations.RenameField(model_name="client", old_name="name", new_name="firstname"),
    ]
