# Generated by Django 3.0.4 on 2020-03-06 14:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0045_auto_20190928_1446")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="client",
            field=models.ForeignKey(
                help_text="Klient, který má zájem o kurz",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="admin.Client",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="course",
            field=models.ForeignKey(
                help_text="Kurz, o který má klient zájem",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="admin.Course",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateField(auto_now_add=True, help_text="Datum vytvoření zájemce o kurz"),
        ),
        migrations.AlterField(
            model_name="application",
            name="note",
            field=models.TextField(blank=True, help_text="Poznámka"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendancestate",
            field=models.ForeignKey(
                help_text="Stav účasti daného klienta na dané lekci",
                on_delete=django.db.models.deletion.PROTECT,
                to="admin.AttendanceState",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="client",
            field=models.ForeignKey(
                help_text="Klient, který se účastní dané lekce",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="admin.Client",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="lecture",
            field=models.ForeignKey(
                help_text="Lekce, ke které tato účast náleží",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="admin.Lecture",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="note",
            field=models.TextField(blank=True, help_text="Poznámka"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="paid",
            field=models.BooleanField(help_text="Indikátor zaplacené lekce"),
        ),
        migrations.AlterField(
            model_name="attendancestate",
            name="default",
            field=models.BooleanField(
                default=False, help_text="Označuje stav (právě jeden), který je výchozí"
            ),
        ),
        migrations.AlterField(
            model_name="attendancestate",
            name="excused",
            field=models.BooleanField(
                default=False, help_text="Označuje stav (právě jeden), který znamená omluven"
            ),
        ),
        migrations.AlterField(
            model_name="attendancestate",
            name="name",
            field=models.TextField(help_text="Název stavu účasti (unikátní)"),
        ),
        migrations.AlterField(
            model_name="attendancestate",
            name="visible",
            field=models.BooleanField(help_text="Indikátor viditelnosti stavu"),
        ),
        migrations.AlterField(
            model_name="client",
            name="active",
            field=models.BooleanField(default=True, help_text="Indikátor aktivity klienta"),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, help_text="Email klienta", max_length=254),
        ),
        migrations.AlterField(
            model_name="client",
            name="firstname",
            field=models.TextField(help_text="Křestní jméno klienta"),
        ),
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(blank=True, help_text="Poznámka"),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.TextField(blank=True, help_text="Telefonní číslo klienta"),
        ),
        migrations.AlterField(
            model_name="client",
            name="surname",
            field=models.TextField(help_text="Příjmení klienta"),
        ),
        migrations.AlterField(
            model_name="course",
            name="color",
            field=models.CharField(
                default="#000000",
                help_text="Kód barvy kurzu",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Barva není v HEX formátu", regex="^#(?:[0-9a-fA-F]{3}){1,2}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="duration",
            field=models.PositiveIntegerField(help_text="Trvání kurzu (min.)"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.TextField(help_text="Název kurzu (unikátní)"),
        ),
        migrations.AlterField(
            model_name="course",
            name="visible",
            field=models.BooleanField(help_text="Indikátor viditelnosti kurzu"),
        ),
        migrations.AlterField(
            model_name="group",
            name="active",
            field=models.BooleanField(default=True, help_text="Indikátor aktivity skupiny"),
        ),
        migrations.AlterField(
            model_name="group",
            name="course",
            field=models.ForeignKey(
                help_text="Kurz skupiny",
                on_delete=django.db.models.deletion.PROTECT,
                to="admin.Course",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.TextField(help_text="Název skupiny (unikátní)"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="canceled",
            field=models.BooleanField(help_text="Indikátor zrušení lekce ze strany lektorky"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="course",
            field=models.ForeignKey(
                help_text="Kurz, ke kterému patří lekce",
                on_delete=django.db.models.deletion.PROTECT,
                to="admin.Course",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="duration",
            field=models.PositiveIntegerField(help_text="Trvání lekce (min.)"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="group",
            field=models.ForeignKey(
                help_text="Skupina, které se tato lekce týká (v případě skupinové lekce)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lectures",
                to="admin.Group",
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="start",
            field=models.DateTimeField(
                help_text="Datum a čas začátku lekce, prázdné pro předplacené lekce bez termínu",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="client",
            field=models.ForeignKey(
                help_text="Klient, který je členem dané skupiny",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="admin.Client",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="group",
            field=models.ForeignKey(
                help_text="Skupina, jejímž členem je daný klient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="admin.Group",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="prepaid_cnt",
            field=models.PositiveIntegerField(
                default=0, help_text="Počet předplacených lekcí klienta v rámci dané skupiny"
            ),
        ),
    ]
