# Generated by Django 3.0.4 on 2020-03-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0046_auto_20200306_1526")]

    operations = [
        migrations.AlterField(
            model_name="attendancestate",
            name="visible",
            field=models.BooleanField(default=True, help_text="Indikátor viditelnosti stavu"),
        ),
        migrations.AlterField(
            model_name="course",
            name="visible",
            field=models.BooleanField(default=True, help_text="Indikátor viditelnosti kurzu"),
        ),
    ]
