# Generated by Django 3.0.5 on 2020-04-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("admin", "0048_auto_20200413_2251")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="note",
            field=models.TextField(blank=True, help_text="Poznámka k zájemci o kurz"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="note",
            field=models.TextField(blank=True, help_text="Poznámka k účasti"),
        ),
        migrations.AlterField(
            model_name="client",
            name="note",
            field=models.TextField(blank=True, help_text="Poznámka ke klientovi"),
        ),
    ]
