# fly.toml app configuration file generated for uspesnyprvnacek-test on 2023-05-28T12:18:58+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "uspesnyprvnacek-test"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "waw"

[experimental]
auto_rollback = true

[deploy]
release_command = "python manage.py migrate --noinput"

[env]
BANK_ACTIVE = "True"
DEBUG = "False"
DEPLOYED = "True"
DJANGO_SETTINGS_MODULE = "up.settings.production"
ENVIRONMENT = "test-fly"
PORT = "8000"

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
