// flow-typed signature: e301eb68894d19afbc3500d026efc4ea
// flow-typed version: <<STUB>>/chroma-js_v^2.0.4/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chroma-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chroma-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chroma-js/chroma-light' {
  declare module.exports: any;
}

declare module 'chroma-js/chroma-light.min' {
  declare module.exports: any;
}

declare module 'chroma-js/chroma' {
  declare module.exports: any;
}

declare module 'chroma-js/chroma.min' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/chroma-light' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/chroma-light.min' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/chroma' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/chroma.min' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/codemirror/lib/codemirror' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/codemirror/mode/javascript/javascript' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/codemirror/mode/javascript/test' {
  declare module.exports: any;
}

declare module 'chroma-js/docs/libs/jquery/jquery-1.11.1.min' {
  declare module.exports: any;
}

declare module 'chroma-js/index-light' {
  declare module.exports: any;
}

declare module 'chroma-js/rollup.config' {
  declare module.exports: any;
}

declare module 'chroma-js/src/chroma' {
  declare module.exports: any;
}

declare module 'chroma-js/src/Color' {
  declare module.exports: any;
}

declare module 'chroma-js/src/colors/colorbrewer' {
  declare module.exports: any;
}

declare module 'chroma-js/src/colors/w3cx11' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/average' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/bezier' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/blend' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/cubehelix' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/mix' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/random' {
  declare module.exports: any;
}

declare module 'chroma-js/src/generator/scale' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/_hsx' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/hcg' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/hsi' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/hsl' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/hsv' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/lab' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/lch' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/lrgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/num' {
  declare module.exports: any;
}

declare module 'chroma-js/src/interpolator/rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/cmyk/cmyk2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/cmyk' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/cmyk/rgb2cmyk' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/css/css2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/css/hsl2css' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/css' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/css/rgb2css' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/gl' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hcg/hcg2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hcg' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hcg/rgb2hcg' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hex/hex2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hex' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hex/rgb2hex' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsi/hsi2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsi' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsi/rgb2hsi' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsl/hsl2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsl' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsl/rgb2hsl' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsv/hsv2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsv' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/hsv/rgb2hsv' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/input' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lab' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lab/lab-constants' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lab/lab2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lab/rgb2lab' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lch/hcl2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lch' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lch/lab2lch' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lch/lch2lab' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lch/lch2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/lch/rgb2lch' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/named' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/num' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/num/num2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/num/rgb2num' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/temp' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/temp/rgb2temperature' {
  declare module.exports: any;
}

declare module 'chroma-js/src/io/temp/temperature2rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/alpha' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/clipped' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/darken' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/get' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/luminance' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/mix' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/premultiply' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/saturate' {
  declare module.exports: any;
}

declare module 'chroma-js/src/ops/set' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/analyze' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/clip_rgb' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/contrast' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/delta-e' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/distance' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/last' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/limit' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/scales' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/type' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/unpack' {
  declare module.exports: any;
}

declare module 'chroma-js/src/utils/valid' {
  declare module.exports: any;
}

declare module 'chroma-js/test/alpha.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/analyze.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/autodetect.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/average.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/bezier' {
  declare module.exports: any;
}

declare module 'chroma-js/test/blend.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/cmyk2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/color.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/contrast.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/converters.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/css2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/cubehelix.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/docs.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/hcg2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/hex2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/hsi2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/hsl2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/hsv2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/lab2lch.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/lab2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/lch.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/lch2lab.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/lch2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/limits.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/luminance.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/manipulate.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/misc.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/mix.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/num.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/num2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/random.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2cmyk.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2css.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2hex.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2hsi.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2hsv.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2lab.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/rgb2lch.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/scale.lcorrection.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/scales.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/temperature2rgb.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/unpack.test' {
  declare module.exports: any;
}

declare module 'chroma-js/test/valid.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chroma-js/chroma-light.js' {
  declare module.exports: $Exports<'chroma-js/chroma-light'>;
}
declare module 'chroma-js/chroma-light.min.js' {
  declare module.exports: $Exports<'chroma-js/chroma-light.min'>;
}
declare module 'chroma-js/chroma.js' {
  declare module.exports: $Exports<'chroma-js/chroma'>;
}
declare module 'chroma-js/chroma.min.js' {
  declare module.exports: $Exports<'chroma-js/chroma.min'>;
}
declare module 'chroma-js/docs/libs/chroma-light.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/chroma-light'>;
}
declare module 'chroma-js/docs/libs/chroma-light.min.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/chroma-light.min'>;
}
declare module 'chroma-js/docs/libs/chroma.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/chroma'>;
}
declare module 'chroma-js/docs/libs/chroma.min.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/chroma.min'>;
}
declare module 'chroma-js/docs/libs/codemirror/lib/codemirror.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/codemirror/lib/codemirror'>;
}
declare module 'chroma-js/docs/libs/codemirror/mode/javascript/javascript.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/codemirror/mode/javascript/javascript'>;
}
declare module 'chroma-js/docs/libs/codemirror/mode/javascript/test.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/codemirror/mode/javascript/test'>;
}
declare module 'chroma-js/docs/libs/jquery/jquery-1.11.1.min.js' {
  declare module.exports: $Exports<'chroma-js/docs/libs/jquery/jquery-1.11.1.min'>;
}
declare module 'chroma-js/index-light.js' {
  declare module.exports: $Exports<'chroma-js/index-light'>;
}
declare module 'chroma-js/index' {
  declare module.exports: $Exports<'chroma-js'>;
}
declare module 'chroma-js/index.js' {
  declare module.exports: $Exports<'chroma-js'>;
}
declare module 'chroma-js/rollup.config.js' {
  declare module.exports: $Exports<'chroma-js/rollup.config'>;
}
declare module 'chroma-js/src/chroma.js' {
  declare module.exports: $Exports<'chroma-js/src/chroma'>;
}
declare module 'chroma-js/src/Color.js' {
  declare module.exports: $Exports<'chroma-js/src/Color'>;
}
declare module 'chroma-js/src/colors/colorbrewer.js' {
  declare module.exports: $Exports<'chroma-js/src/colors/colorbrewer'>;
}
declare module 'chroma-js/src/colors/w3cx11.js' {
  declare module.exports: $Exports<'chroma-js/src/colors/w3cx11'>;
}
declare module 'chroma-js/src/generator/average.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/average'>;
}
declare module 'chroma-js/src/generator/bezier.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/bezier'>;
}
declare module 'chroma-js/src/generator/blend.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/blend'>;
}
declare module 'chroma-js/src/generator/cubehelix.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/cubehelix'>;
}
declare module 'chroma-js/src/generator/mix.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/mix'>;
}
declare module 'chroma-js/src/generator/random.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/random'>;
}
declare module 'chroma-js/src/generator/scale.js' {
  declare module.exports: $Exports<'chroma-js/src/generator/scale'>;
}
declare module 'chroma-js/src/interpolator/_hsx.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/_hsx'>;
}
declare module 'chroma-js/src/interpolator/hcg.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/hcg'>;
}
declare module 'chroma-js/src/interpolator/hsi.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/hsi'>;
}
declare module 'chroma-js/src/interpolator/hsl.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/hsl'>;
}
declare module 'chroma-js/src/interpolator/hsv.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/hsv'>;
}
declare module 'chroma-js/src/interpolator/index' {
  declare module.exports: $Exports<'chroma-js/src/interpolator'>;
}
declare module 'chroma-js/src/interpolator/index.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator'>;
}
declare module 'chroma-js/src/interpolator/lab.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/lab'>;
}
declare module 'chroma-js/src/interpolator/lch.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/lch'>;
}
declare module 'chroma-js/src/interpolator/lrgb.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/lrgb'>;
}
declare module 'chroma-js/src/interpolator/num.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/num'>;
}
declare module 'chroma-js/src/interpolator/rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/interpolator/rgb'>;
}
declare module 'chroma-js/src/io/cmyk/cmyk2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/cmyk/cmyk2rgb'>;
}
declare module 'chroma-js/src/io/cmyk/index' {
  declare module.exports: $Exports<'chroma-js/src/io/cmyk'>;
}
declare module 'chroma-js/src/io/cmyk/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/cmyk'>;
}
declare module 'chroma-js/src/io/cmyk/rgb2cmyk.js' {
  declare module.exports: $Exports<'chroma-js/src/io/cmyk/rgb2cmyk'>;
}
declare module 'chroma-js/src/io/css/css2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/css/css2rgb'>;
}
declare module 'chroma-js/src/io/css/hsl2css.js' {
  declare module.exports: $Exports<'chroma-js/src/io/css/hsl2css'>;
}
declare module 'chroma-js/src/io/css/index' {
  declare module.exports: $Exports<'chroma-js/src/io/css'>;
}
declare module 'chroma-js/src/io/css/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/css'>;
}
declare module 'chroma-js/src/io/css/rgb2css.js' {
  declare module.exports: $Exports<'chroma-js/src/io/css/rgb2css'>;
}
declare module 'chroma-js/src/io/gl/index' {
  declare module.exports: $Exports<'chroma-js/src/io/gl'>;
}
declare module 'chroma-js/src/io/gl/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/gl'>;
}
declare module 'chroma-js/src/io/hcg/hcg2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hcg/hcg2rgb'>;
}
declare module 'chroma-js/src/io/hcg/index' {
  declare module.exports: $Exports<'chroma-js/src/io/hcg'>;
}
declare module 'chroma-js/src/io/hcg/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hcg'>;
}
declare module 'chroma-js/src/io/hcg/rgb2hcg.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hcg/rgb2hcg'>;
}
declare module 'chroma-js/src/io/hex/hex2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hex/hex2rgb'>;
}
declare module 'chroma-js/src/io/hex/index' {
  declare module.exports: $Exports<'chroma-js/src/io/hex'>;
}
declare module 'chroma-js/src/io/hex/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hex'>;
}
declare module 'chroma-js/src/io/hex/rgb2hex.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hex/rgb2hex'>;
}
declare module 'chroma-js/src/io/hsi/hsi2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsi/hsi2rgb'>;
}
declare module 'chroma-js/src/io/hsi/index' {
  declare module.exports: $Exports<'chroma-js/src/io/hsi'>;
}
declare module 'chroma-js/src/io/hsi/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsi'>;
}
declare module 'chroma-js/src/io/hsi/rgb2hsi.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsi/rgb2hsi'>;
}
declare module 'chroma-js/src/io/hsl/hsl2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsl/hsl2rgb'>;
}
declare module 'chroma-js/src/io/hsl/index' {
  declare module.exports: $Exports<'chroma-js/src/io/hsl'>;
}
declare module 'chroma-js/src/io/hsl/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsl'>;
}
declare module 'chroma-js/src/io/hsl/rgb2hsl.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsl/rgb2hsl'>;
}
declare module 'chroma-js/src/io/hsv/hsv2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsv/hsv2rgb'>;
}
declare module 'chroma-js/src/io/hsv/index' {
  declare module.exports: $Exports<'chroma-js/src/io/hsv'>;
}
declare module 'chroma-js/src/io/hsv/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsv'>;
}
declare module 'chroma-js/src/io/hsv/rgb2hsv.js' {
  declare module.exports: $Exports<'chroma-js/src/io/hsv/rgb2hsv'>;
}
declare module 'chroma-js/src/io/input.js' {
  declare module.exports: $Exports<'chroma-js/src/io/input'>;
}
declare module 'chroma-js/src/io/lab/index' {
  declare module.exports: $Exports<'chroma-js/src/io/lab'>;
}
declare module 'chroma-js/src/io/lab/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lab'>;
}
declare module 'chroma-js/src/io/lab/lab-constants.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lab/lab-constants'>;
}
declare module 'chroma-js/src/io/lab/lab2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lab/lab2rgb'>;
}
declare module 'chroma-js/src/io/lab/rgb2lab.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lab/rgb2lab'>;
}
declare module 'chroma-js/src/io/lch/hcl2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lch/hcl2rgb'>;
}
declare module 'chroma-js/src/io/lch/index' {
  declare module.exports: $Exports<'chroma-js/src/io/lch'>;
}
declare module 'chroma-js/src/io/lch/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lch'>;
}
declare module 'chroma-js/src/io/lch/lab2lch.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lch/lab2lch'>;
}
declare module 'chroma-js/src/io/lch/lch2lab.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lch/lch2lab'>;
}
declare module 'chroma-js/src/io/lch/lch2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lch/lch2rgb'>;
}
declare module 'chroma-js/src/io/lch/rgb2lch.js' {
  declare module.exports: $Exports<'chroma-js/src/io/lch/rgb2lch'>;
}
declare module 'chroma-js/src/io/named/index' {
  declare module.exports: $Exports<'chroma-js/src/io/named'>;
}
declare module 'chroma-js/src/io/named/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/named'>;
}
declare module 'chroma-js/src/io/num/index' {
  declare module.exports: $Exports<'chroma-js/src/io/num'>;
}
declare module 'chroma-js/src/io/num/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/num'>;
}
declare module 'chroma-js/src/io/num/num2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/num/num2rgb'>;
}
declare module 'chroma-js/src/io/num/rgb2num.js' {
  declare module.exports: $Exports<'chroma-js/src/io/num/rgb2num'>;
}
declare module 'chroma-js/src/io/rgb/index' {
  declare module.exports: $Exports<'chroma-js/src/io/rgb'>;
}
declare module 'chroma-js/src/io/rgb/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/rgb'>;
}
declare module 'chroma-js/src/io/temp/index' {
  declare module.exports: $Exports<'chroma-js/src/io/temp'>;
}
declare module 'chroma-js/src/io/temp/index.js' {
  declare module.exports: $Exports<'chroma-js/src/io/temp'>;
}
declare module 'chroma-js/src/io/temp/rgb2temperature.js' {
  declare module.exports: $Exports<'chroma-js/src/io/temp/rgb2temperature'>;
}
declare module 'chroma-js/src/io/temp/temperature2rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/io/temp/temperature2rgb'>;
}
declare module 'chroma-js/src/ops/alpha.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/alpha'>;
}
declare module 'chroma-js/src/ops/clipped.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/clipped'>;
}
declare module 'chroma-js/src/ops/darken.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/darken'>;
}
declare module 'chroma-js/src/ops/get.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/get'>;
}
declare module 'chroma-js/src/ops/luminance.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/luminance'>;
}
declare module 'chroma-js/src/ops/mix.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/mix'>;
}
declare module 'chroma-js/src/ops/premultiply.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/premultiply'>;
}
declare module 'chroma-js/src/ops/saturate.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/saturate'>;
}
declare module 'chroma-js/src/ops/set.js' {
  declare module.exports: $Exports<'chroma-js/src/ops/set'>;
}
declare module 'chroma-js/src/utils/analyze.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/analyze'>;
}
declare module 'chroma-js/src/utils/clip_rgb.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/clip_rgb'>;
}
declare module 'chroma-js/src/utils/contrast.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/contrast'>;
}
declare module 'chroma-js/src/utils/delta-e.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/delta-e'>;
}
declare module 'chroma-js/src/utils/distance.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/distance'>;
}
declare module 'chroma-js/src/utils/index' {
  declare module.exports: $Exports<'chroma-js/src/utils'>;
}
declare module 'chroma-js/src/utils/index.js' {
  declare module.exports: $Exports<'chroma-js/src/utils'>;
}
declare module 'chroma-js/src/utils/last.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/last'>;
}
declare module 'chroma-js/src/utils/limit.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/limit'>;
}
declare module 'chroma-js/src/utils/scales.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/scales'>;
}
declare module 'chroma-js/src/utils/type.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/type'>;
}
declare module 'chroma-js/src/utils/unpack.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/unpack'>;
}
declare module 'chroma-js/src/utils/valid.js' {
  declare module.exports: $Exports<'chroma-js/src/utils/valid'>;
}
declare module 'chroma-js/test/alpha.test.js' {
  declare module.exports: $Exports<'chroma-js/test/alpha.test'>;
}
declare module 'chroma-js/test/analyze.test.js' {
  declare module.exports: $Exports<'chroma-js/test/analyze.test'>;
}
declare module 'chroma-js/test/autodetect.test.js' {
  declare module.exports: $Exports<'chroma-js/test/autodetect.test'>;
}
declare module 'chroma-js/test/average.test.js' {
  declare module.exports: $Exports<'chroma-js/test/average.test'>;
}
declare module 'chroma-js/test/bezier.js' {
  declare module.exports: $Exports<'chroma-js/test/bezier'>;
}
declare module 'chroma-js/test/blend.test.js' {
  declare module.exports: $Exports<'chroma-js/test/blend.test'>;
}
declare module 'chroma-js/test/cmyk2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/cmyk2rgb.test'>;
}
declare module 'chroma-js/test/color.test.js' {
  declare module.exports: $Exports<'chroma-js/test/color.test'>;
}
declare module 'chroma-js/test/contrast.test.js' {
  declare module.exports: $Exports<'chroma-js/test/contrast.test'>;
}
declare module 'chroma-js/test/converters.test.js' {
  declare module.exports: $Exports<'chroma-js/test/converters.test'>;
}
declare module 'chroma-js/test/css2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/css2rgb.test'>;
}
declare module 'chroma-js/test/cubehelix.test.js' {
  declare module.exports: $Exports<'chroma-js/test/cubehelix.test'>;
}
declare module 'chroma-js/test/docs.test.js' {
  declare module.exports: $Exports<'chroma-js/test/docs.test'>;
}
declare module 'chroma-js/test/hcg2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/hcg2rgb.test'>;
}
declare module 'chroma-js/test/hex2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/hex2rgb.test'>;
}
declare module 'chroma-js/test/hsi2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/hsi2rgb.test'>;
}
declare module 'chroma-js/test/hsl2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/hsl2rgb.test'>;
}
declare module 'chroma-js/test/hsv2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/hsv2rgb.test'>;
}
declare module 'chroma-js/test/lab2lch.test.js' {
  declare module.exports: $Exports<'chroma-js/test/lab2lch.test'>;
}
declare module 'chroma-js/test/lab2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/lab2rgb.test'>;
}
declare module 'chroma-js/test/lch.test.js' {
  declare module.exports: $Exports<'chroma-js/test/lch.test'>;
}
declare module 'chroma-js/test/lch2lab.test.js' {
  declare module.exports: $Exports<'chroma-js/test/lch2lab.test'>;
}
declare module 'chroma-js/test/lch2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/lch2rgb.test'>;
}
declare module 'chroma-js/test/limits.test.js' {
  declare module.exports: $Exports<'chroma-js/test/limits.test'>;
}
declare module 'chroma-js/test/luminance.test.js' {
  declare module.exports: $Exports<'chroma-js/test/luminance.test'>;
}
declare module 'chroma-js/test/manipulate.test.js' {
  declare module.exports: $Exports<'chroma-js/test/manipulate.test'>;
}
declare module 'chroma-js/test/misc.test.js' {
  declare module.exports: $Exports<'chroma-js/test/misc.test'>;
}
declare module 'chroma-js/test/mix.test.js' {
  declare module.exports: $Exports<'chroma-js/test/mix.test'>;
}
declare module 'chroma-js/test/num.test.js' {
  declare module.exports: $Exports<'chroma-js/test/num.test'>;
}
declare module 'chroma-js/test/num2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/num2rgb.test'>;
}
declare module 'chroma-js/test/random.test.js' {
  declare module.exports: $Exports<'chroma-js/test/random.test'>;
}
declare module 'chroma-js/test/rgb2cmyk.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2cmyk.test'>;
}
declare module 'chroma-js/test/rgb2css.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2css.test'>;
}
declare module 'chroma-js/test/rgb2hex.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2hex.test'>;
}
declare module 'chroma-js/test/rgb2hsi.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2hsi.test'>;
}
declare module 'chroma-js/test/rgb2hsv.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2hsv.test'>;
}
declare module 'chroma-js/test/rgb2lab.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2lab.test'>;
}
declare module 'chroma-js/test/rgb2lch.test.js' {
  declare module.exports: $Exports<'chroma-js/test/rgb2lch.test'>;
}
declare module 'chroma-js/test/scale.lcorrection.test.js' {
  declare module.exports: $Exports<'chroma-js/test/scale.lcorrection.test'>;
}
declare module 'chroma-js/test/scales.test.js' {
  declare module.exports: $Exports<'chroma-js/test/scales.test'>;
}
declare module 'chroma-js/test/temperature2rgb.test.js' {
  declare module.exports: $Exports<'chroma-js/test/temperature2rgb.test'>;
}
declare module 'chroma-js/test/unpack.test.js' {
  declare module.exports: $Exports<'chroma-js/test/unpack.test'>;
}
declare module 'chroma-js/test/valid.test.js' {
  declare module.exports: $Exports<'chroma-js/test/valid.test'>;
}
