// flow-typed signature: 8cea37e9047f3943a262ebc157807a7d
// flow-typed version: <<STUB>>/clean-webpack-plugin_v^3.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clean-webpack-plugin/dist/clean-webpack-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clean-webpack-plugin/dist/clean-webpack-plugin.js' {
  declare module.exports: $Exports<'clean-webpack-plugin/dist/clean-webpack-plugin'>;
}
