// flow-typed signature: bbe788963e1fe3dcc3bcfeffd3e26823
// flow-typed version: <<STUB>>/confusing-browser-globals_v^1.0.9/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'confusing-browser-globals'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'confusing-browser-globals' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'confusing-browser-globals/index' {
  declare module.exports: $Exports<'confusing-browser-globals'>;
}
declare module 'confusing-browser-globals/index.js' {
  declare module.exports: $Exports<'confusing-browser-globals'>;
}
