// flow-typed signature: 97ee5b9d5464547b9e0161f4a8e8633b
// flow-typed version: <<STUB>>/eslint-loader_v^3.0.3/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-loader/dist/cacheLoader' {
  declare module.exports: any;
}

declare module 'eslint-loader/dist/cjs' {
  declare module.exports: any;
}

declare module 'eslint-loader/dist/createEngine' {
  declare module.exports: any;
}

declare module 'eslint-loader/dist/ESLintError' {
  declare module.exports: any;
}

declare module 'eslint-loader/dist/getOptions' {
  declare module.exports: any;
}

declare module 'eslint-loader/dist' {
  declare module.exports: any;
}

declare module 'eslint-loader/dist/Linter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-loader/dist/cacheLoader.js' {
  declare module.exports: $Exports<'eslint-loader/dist/cacheLoader'>;
}
declare module 'eslint-loader/dist/cjs.js' {
  declare module.exports: $Exports<'eslint-loader/dist/cjs'>;
}
declare module 'eslint-loader/dist/createEngine.js' {
  declare module.exports: $Exports<'eslint-loader/dist/createEngine'>;
}
declare module 'eslint-loader/dist/ESLintError.js' {
  declare module.exports: $Exports<'eslint-loader/dist/ESLintError'>;
}
declare module 'eslint-loader/dist/getOptions.js' {
  declare module.exports: $Exports<'eslint-loader/dist/getOptions'>;
}
declare module 'eslint-loader/dist/index' {
  declare module.exports: $Exports<'eslint-loader/dist'>;
}
declare module 'eslint-loader/dist/index.js' {
  declare module.exports: $Exports<'eslint-loader/dist'>;
}
declare module 'eslint-loader/dist/Linter.js' {
  declare module.exports: $Exports<'eslint-loader/dist/Linter'>;
}
