// flow-typed signature: 82c1da0adb64ffec64f8039e03a34d7c
// flow-typed version: <<STUB>>/react-toastify_v^5.1.0/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toastify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toastify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toastify/cjs/react-toastify' {
  declare module.exports: any;
}

declare module 'react-toastify/cjs/react-toastify.min' {
  declare module.exports: any;
}

declare module 'react-toastify/esm/react-toastify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toastify/cjs/react-toastify.js' {
  declare module.exports: $Exports<'react-toastify/cjs/react-toastify'>;
}
declare module 'react-toastify/cjs/react-toastify.min.js' {
  declare module.exports: $Exports<'react-toastify/cjs/react-toastify.min'>;
}
declare module 'react-toastify/esm/react-toastify.js' {
  declare module.exports: $Exports<'react-toastify/esm/react-toastify'>;
}
declare module 'react-toastify/index' {
  declare module.exports: $Exports<'react-toastify'>;
}
declare module 'react-toastify/index.js' {
  declare module.exports: $Exports<'react-toastify'>;
}
